name: ci

on:
  pull_request:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: jdx/mise-action@v3.2.0
      - run: mise install
